#!/usr/bin/env python3
"""Convert an 8x16 PSF1 console font into JellyOS's built-in font table.

usage: psf2c.py FONT.psf[.gz] OUTPUT.c

The output maps every Latin-1 code point (0-255) to a 16-byte glyph, using
the font's Unicode table. Code points the font lacks get an empty glyph
(controls) or the replacement box. The generated file is checked in
(graphics/core/font8x16.c), so builds do not need the host font.

Source used: Lat15-Fixed16 from console-setup (derived from the X11
"fixed" font; console fonts are public domain).
"""

import gzip
import sys


def load_psf1(path):
    data = open(path, "rb").read()
    if data[:2] == b"\x1f\x8b":
        data = gzip.decompress(data)
    if data[:2] != b"\x36\x04":
        sys.exit("psf2c: only PSF1 fonts are supported")
    mode, height = data[2], data[3]
    if height != 16:
        sys.exit("psf2c: the font must be 8x16")
    count = 512 if mode & 1 else 256
    glyphs = [data[4 + i * 16:4 + (i + 1) * 16] for i in range(count)]
    table = {}
    if mode & 2:  # Unicode table: per glyph, code points until 0xFFFF
        offset = 4 + count * 16
        for glyph in range(count):
            in_sequence = False
            while True:
                value = int.from_bytes(data[offset:offset + 2], "little")
                offset += 2
                if value == 0xFFFF:
                    break
                if value == 0xFFFE:
                    in_sequence = True
                    continue
                if not in_sequence:
                    table.setdefault(value, glyph)
    else:
        table = {i: i for i in range(count)}
    return glyphs, table


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip().splitlines()[2])
    glyphs, table = load_psf1(sys.argv[1])
    replacement = glyphs[table[0xFFFD]] if 0xFFFD in table else bytes([0, 0, 0x7E, 0x42, 0x42, 0x42, 0x42, 0x42,
                                                                         0x42, 0x42, 0x42, 0x42, 0x7E, 0, 0, 0])
    lines = [
        "/*",
        " * Built-in 8x16 bitmap font, indexed by Latin-1 code point (generated by",
        " * tools/fontgen/psf2c.py from Lat15-Fixed16, console-setup, public domain).",
        " * Each glyph is 16 rows of 8 pixels, most significant bit leftmost.",
        " */",
        "",
        '#include "graphics/core/font.h"',
        "",
        "const uint8_t font8x16[256][16] = {",
    ]
    for code in range(256):
        if code < 0x20 or 0x7F <= code < 0xA0:
            glyph = bytes(16)
        elif code in table:
            glyph = glyphs[table[code]]
        else:
            glyph = replacement
        label = chr(code) if 0x20 < code < 0x7F and chr(code) not in "\\'" else f"U+{code:04X}"
        lines.append("    { " + ", ".join(f"0x{b:02X}" for b in glyph) + f" }}, /* {label} */")
    lines.append("};")
    open(sys.argv[2], "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
