#!/usr/bin/env python3
"""Generate the kernel symbol table (kernel/core/ksyms.h) for stack traces.

Usage:
    ksyms.py --empty            > empty.c   # placeholder for the first link
    nm -n --defined-only kernel | ksyms.py > table.c

Only text symbols are included. The table is placed in .rodata, after .text,
so adding it to the final link does not move any function.
"""

import sys

TEXT_TYPES = set("TtWw")


def rank(name, kind):
    """Lower is better: functions before linker-script markers, globals before locals."""
    return (name.startswith("__"), not kind.isupper())


def parse(lines):
    symbols = {}
    for line in lines:
        parts = line.split()
        if len(parts) != 3 or parts[1] not in TEXT_TYPES:
            continue
        address = int(parts[0], 16)
        name, kind = parts[2], parts[1]
        if address not in symbols or rank(name, kind) < rank(*symbols[address]):
            symbols[address] = (name, kind)
    return sorted((address, name) for address, (name, _) in symbols.items())


def emit(symbols, out):
    out.write("/* Generated by tools/debugger/ksyms.py - do not edit. */\n")
    out.write('#include "core/ksyms.h"\n\n')
    if not symbols:
        out.write("const ksym_t ksym_table[1] = { { 0, 0 } };\n")
        out.write("const size_t ksym_count = 0;\n")
        return
    out.write("const ksym_t ksym_table[] = {\n")
    for address, name in symbols:
        out.write('    { 0x%016xULL, "%s" },\n' % (address, name.replace("\\", "\\\\").replace('"', '\\"')))
    out.write("};\n")
    out.write("const size_t ksym_count = %d;\n" % len(symbols))


def main():
    symbols = [] if "--empty" in sys.argv[1:] else parse(sys.stdin)
    emit(symbols, sys.stdout)


if __name__ == "__main__":
    main()
